services:
  bao37-web:
    build:
      context: .
      dockerfile: web/Dockerfile
    container_name: bao37-web
    restart: unless-stopped
    labels:
      traefik.enable: "true"

      traefik.http.routers.bao37.rule: "Host(`bao37.fr`) || Host(`www.bao37.fr`)"
      traefik.http.routers.bao37.entrypoints: "web"

      traefik.http.services.bao37.loadbalancer.server.port: "80"